local Color, colors, Group, groups, styles = require("colorbuddy").setup()

Color.new('nord_0', "#21222C")
Color.new('nord_1',"#FF5555")
Color.new('nord_2', "#50FA7B")
Color.new('nord_3', "#F1FA8C")
Color.new('nord_3_light', "#616E88")
Color.new('nord_4',  "#BD93F9")
Color.new('nord_5',  "#FF79C6")
Color.new('nord_6',  "#8BE9FD")
Color.new('nord_7',  "#F8F8F2")
Color.new('nord_8',  "#6272A4")
Color.new('nord_9',  "#FF6E6E")
Color.new('nord_10', "#69FF94")
Color.new('nord_11', "#FFFFA5")
Color.new('nord_12', "#D6ACFF")
Color.new('nord_13', "#FF92DF")
Color.new('nord_14', "#A4FFFF")
Color.new('nord_15', "#FFFFFF")

Color.new('cyan',      '#8be9fd')
Color.new('green',     '#50fa7b')
Color.new('orange',    '#ffb86c')
Color.new('pink',      '#ff79c6')
Color.new('purple',    '#bd93f9')
Color.new('red',       '#ff5555')
Color.new('yellow',    '#f1fa8c')
Color.new('bg', '#282a36')
Color.new('bglight', '#343746')

Color.new('fg', '#f8f8f2')
Color.new('comment', '#6272a4')
Color.new('subtle', '#424450')
Color.new('selection', '#44475A')

-- my highlight
Group.new('TabLineSel',          colors.fg,           colors.blue, styles.bold )
Group.new('TabLineSelSeparator', colors.blue,         colors.none)
Group.new('TabLine', colors.nord_4, colors.nord_2)
Group.new('TabLineSeparator', colors.nord_2, colors.none)

Group.new('Conceal',             colors.subtle, colors.none)
Group.new('VertSplit', colors.comment, colors.bg)

Group.new('Normal',         colors.none,         colors.none)
Group.new("Function",       colors.green,       colors.none,    styles.NONE)
Group.new('Error',          colors.red,      colors.none,    styles.bold)
Group.new('ErrorMsg',       colors.fg,       colors.red, styles.bold)
Group.new('WarningMsg',     colors.fg,       colors.orange, styles.bold)
Group.new('Boolean',        colors.purple,       colors.none,    styles.NONE)
Group.new('Character',      colors.pink,      colors.none,    styles.NONE)
Group.new('Comment',        colors.comment, colors.none,    styles.italic)
Group.new("Conditional",    colors.purple,       colors.none,    styles.italic)
Group.new("Constant",       colors.purple,       colors.none,    styles.italic)
Group.new("Define",         colors.pink,       colors.none,    styles.NONE)
Group.new("Delimiter",      colors.fg,       colors.none,    styles.NONE)
Group.new("Exception",      colors.pink,       colors.none,    styles.NONE)
Group.new("Float",          colors.purple,      colors.none,    styles.NONE)
Group.new("Identifier",     colors.fg,       colors.none,    styles.NONE)
Group.new("Include",        colors.cyan,       colors.none,    styles.NONE)
Group.new("Keyword",        colors.purple,       colors.none,    styles.italic)
Group.new("Label",          colors.pink,       colors.none,    styles.NONE)
Group.new("Number",         colors.purple,      colors.none,    styles.NONE)
Group.new("Operator",       colors.pink,       colors.none,    styles.NONE)
Group.new("PreProc",        colors.pink,       colors.none,    styles.NONE)
Group.new("Repeat",         colors.pink,       colors.none,    styles.NONE)
Group.new("Special",        colors.pink,       colors.none,    styles.NONE)
Group.new("SpecialComment", colors.cyan,       colors.none,    styles.italic)
Group.new("Statement",      colors.pink,       colors.none,    styles.NONE)
Group.new("StorageClass",   colors.pink,       colors.none,    styles.NONE)
Group.new("String",         colors.yellow,      colors.none,    styles.NONE)
Group.new("Structure",      colors.pink,       colors.none,    styles.NONE)
Group.new("Tag",            colors.cyan,       colors.none,    styles.NONE)
Group.new("Title",          colors.green,       colors.none, styles.bold)
Group.new("Todo",           colors.cyan,      colors.none,    styles.NONE)
Group.new("Type",           colors.cyan,       colors.none,    styles.italic)
Group.new("Typedef",        colors.pink,       colors.none,    styles.NONE)
Group.new("CursorColumn",   colors.none,       colors.subtle,    styles.NONE)
Group.new("LineNr",         colors.nord_8,       colors.none,    styles.NONE)
Group.new("CursorLineNr",   colors.yellow,       colors.none,    styles.NONE)
Group.new("Line",           colors.nord_12,      colors.none,    styles.bold)
Group.new("SignColumn",     colors.none,         colors.none,    styles.NONE)
Group.new("StatusLine",     colors.fg,       colors.bg,    styles.NONE)
Group.new("Macro",     colors.pink,       colors.none,    styles.NONE)
Group.new("PreCondit",     colors.pink,       colors.none,    styles.NONE)

Group.new("ColorColumn", colors.none, colors.nord_1)
Group.new("Cursor", colors.nord_0, colors.nord_4)
Group.new("CursorLine", colors.none, colors.bglight)
Group.new("iCursor",colors.nord_0, colors.nord_4)
Group.new("EndOfBuffer",colors.none, colors.none)
Group.new("MatchParen",colors.purple, colors.none, styles.underline)
Group.new("NonText",colors.none, colors.none)
Group.new("PMenu", colors.bg, colors.bglight)
Group.new("CmpItemMenu", groups.PMenu)
Group.new("CmpItemAbbr", colors.pink, colors.none)
Group.new("CmpItemKind", colors.green, colors.none)
Group.new("CmpItemAbbrMatchFuzzy", colors.purple, colors.none)
Group.new("PmenuSbar", colors.bg, colors.bglight)
Group.new("PMenuSel", colors.bg, colors.selection)
Group.new("PmenuThumb", colors.bg, colors.selection)
Group.new("SpecialKey",colors.nord_3, colors.nord_3)
Group.new("SpellBad",colors.nord_11, colors.nord_0)
Group.new("SpellCap",colors.nord_13, colors.nord_0)
Group.new("SpellLocal",colors.nord_5, colors.nord_0)
Group.new("SpellRare",colors.nord_6, colors.nord_0)
Group.new("Visual",colors.none, colors.selection)
Group.new("VisualNOS",colors.none, colors.selection)
Group.new("Folded", colors.nord_14, colors.none, styles.italic)

-- "+- Neovim Support -+
Group.new("healthError",colors.nord_11, colors.nord_1)
Group.new("healthSuccess",colors.nord_14, colors.nord_1)
Group.new("healthWarning",colors.nord_13, colors.nord_1)
Group.new("TermCursorNC",colors.nord_1, colors.nord_1)
Group.new("IncSearch",colors.bg, colors.orange, styles.underline)
Group.new("Search",colors.fg, colors.selection, styles.underline)

-- vim
Group.new('vimcommand',      groups.Statement, colors.none)
Group.new('vimLet',          groups.vimcommand , colors.none)
Group.new('vimFuncVar',      groups.identifier, colors.none)
Group.new('vimCommentTitle', groups.PreProc, colors.none)
Group.new('vimIsCommand',    colors.none, colors.none)
Group.new('vimFuncSID',      groups.Special, colors.none)
Group.new('vimMapModKey',    groups.vimFuncSID, colors.none)
Group.new('vimMapLhs',       colors.none, colors.none)
Group.new('vimNotation',     colors.nord_7, colors.none)
Group.new('vimBracket',      groups.Delimiter, colors.none)
Group.new('vimMap',          groups.vimcommand, colors.none)
Group.new('nvimMap',         groups.vimMap, colors.none)

-- startify
Group.new("StartifyFile",colors.nord_6, colors.none)
Group.new("StartifyFooter",colors.none, colors.none)
Group.new("StartifyHeader",colors.nord_8, colors.none)
Group.new("StartifyNumber",colors.nord_7, colors.none)
Group.new("StartifyPath",colors.nord_8, colors.none)
Group.new("StartifyBracket", groups.Delimiter, groups.Delimiter)
Group.new("StartifySlash", groups.Normal, groups.Normal)
Group.new("StartifySpecial", groups.Comment, groups.Comment)

-- gitgutter
Group.new("GitGutterAdd",          colors.nord_14, colors.none)
Group.new("GitGutterDelete",       colors.nord_11, colors.none)
Group.new("GitGutterChange",       colors.nord_13, colors.none)
Group.new("GitGutterChangeDelete", colors.nord_11, colors.none)

-- built-in LSP
Group.new("LSPDiagnosticsDefaultWarning", colors.yellow, colors.none)
Group.new("LSPDiagnosticsDefaultError", colors.red, colors.none)
Group.new("LSPDiagnosticsDefaultInformation", colors.green, colors.none)
Group.new("LSPDiagnosticsDefaultHint", colors.cyan, colors.none)
Group.new("LSPDiagnosticsSignWarning", colors.yellow, colors.none)
Group.new("LSPDiagnosticsSignError", colors.red, colors.none)
Group.new("LSPDiagnosticsSignInformation", colors.green, colors.none)
Group.new("LSPDiagnosticsSignHint", colors.cyan, colors.none)
Group.new("LSPDiagnosticsFloatingWarning", colors.yellow, colors.none)
Group.new("LSPDiagnosticsFloatingError", colors.red, colors.none)
Group.new("LSPDiagnosticsFloatingInformation", colors.green, colors.none)
Group.new("LSPDiagnosticsFloatingHint", colors.cyan, colors.none)

Group.new("LSPReferenceText", colors.none, colors.none)
Group.new("LSPReferenceRead", colors.none, colors.none, styles.bold)
Group.new("LSPReferenceWrite", colors.nord_9, colors.none, styles.bold)

-- TeleScope
Group.new("TelescopeSelection", colors.nord_11, colors.nord_8, styles.bold)
Group.new("TelescopeNormal", groups.Pmenu, groups.Pmenu)

-- Markdown
Group.new("markdownError", colors.nord_4, colors.none)

-- TS
Group.new("TSMath", colors.fg, colors.none)
Group.new("TSEnvironment", colors.purple, colors.none)
